[project]
name = "nlp-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "afinn>=0.1",
    "dotenv>=0.9.9",
    "fastapi>=0.128.2",
    "httpx>=0.28.1",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
]
